dist: bionic

language: python

python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt

script:
  - make lint
  - make test
  - make build
  - make install
  - make run
  - make uninstall
  - make clean

  notifications:
    email: false
